# Generated by Django 4.2.6 on 2023-10-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contractorregister',
            fields=[
                ('ContractorId', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone_No', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=8)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.BooleanField(default=False)),
                ('Profile_pic', models.ImageField(blank=True, null=True, upload_to='profile1/')),
                ('User', models.CharField(choices=[('admin', 'ADMIN'), ('customer', 'CUSTOMER'), ('worker', 'WORKER'), ('contractor', 'CONTRACTOR')], default='CONTRACTOR', max_length=12)),
                ('Rate', models.FloatField(max_length=10)),
                ('Id_Proof', models.ImageField(blank=True, null=True, upload_to='proof/')),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone_No', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=8)),
                ('Profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('User', models.CharField(choices=[('admin', 'ADMIN'), ('customer', 'CUSTOMER'), ('worker', 'WORKER'), ('contractor', 'CONTRACTOR')], default='CUSTOMER', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='workerregister',
            fields=[
                ('workerId', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone_No', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=8)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.BooleanField(default=False)),
                ('Status', models.BooleanField(default=False)),
                ('Profile_pic', models.ImageField(blank=True, null=True, upload_to='profile2/')),
                ('User', models.CharField(choices=[('admin', 'ADMIN'), ('customer', 'CUSTOMER'), ('worker', 'WORKER'), ('contractor', 'CONTRACTOR')], default='WORKER', max_length=12)),
                ('Wage', models.FloatField(max_length=10)),
                ('Id_Proof', models.ImageField(blank=True, null=True, upload_to='proof/')),
            ],
        ),
    ]
