# Generated by Django 4.2.6 on 2023-10-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0003_contractorregister_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('workId', models.AutoField(primary_key=True, serialize=False)),
                ('work_type', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contractorregister',
            name='Active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workerregister',
            name='Active_status',
            field=models.BooleanField(default=True),
        ),
    ]
