# Generated by Django 4.2.6 on 2023-10-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0004_work_contractorregister_active_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('serviceId', models.AutoField(primary_key=True, serialize=False)),
                ('Wage', models.FloatField(max_length=10)),
                ('workId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapp.work')),
                ('workerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapp.workerregister')),
            ],
        ),
    ]
