# Generated by Django 4.2.6 on 2023-10-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0005_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='workId',
        ),
        migrations.AddField(
            model_name='service',
            name='works',
            field=models.ManyToManyField(to='buildapp.work'),
        ),
    ]
