# Generated by Django 4.2.6 on 2023-10-25 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0006_remove_service_workid_service_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='previous_designs',
            fields=[
                ('designId', models.AutoField(primary_key=True, serialize=False)),
                ('Caption', models.CharField(max_length=25)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('ContractorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapp.contractorregister')),
            ],
        ),
    ]
