# Generated by Django 4.2.6 on 2023-10-28 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0008_worker_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('serviceId', models.AutoField(primary_key=True, serialize=False)),
                ('Wage', models.FloatField(max_length=10)),
                ('workerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapp.workerregister')),
                ('works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapp.work')),
            ],
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
