# Generated by Django 4.2.6 on 2023-10-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0010_services_wage1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Wage1',
        ),
    ]
