# Generated by Django 4.2.6 on 2023-10-29 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0012_alter_worker_req_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicescontractor',
            fields=[
                ('serviceId', models.AutoField(primary_key=True, serialize=False)),
                ('Rate', models.FloatField(max_length=10)),
                ('ContractorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapp.contractorregister')),
                ('works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapp.work')),
            ],
        ),
        migrations.CreateModel(
            name='contractor_req',
            fields=[
                ('ReqId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Status', models.BooleanField(default=False)),
                ('ContractorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapp.contractorregister')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapp.register')),
                ('workId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapp.work')),
            ],
        ),
    ]
