# Generated by Django 4.2.6 on 2023-11-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0013_servicescontractor_contractor_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_req',
            name='workstatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='previous_designs',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='design/'),
        ),
    ]
