# Generated by Django 4.2.6 on 2023-11-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0014_worker_req_workstatus_alter_previous_designs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_req',
            name='Wages',
            field=models.CharField(default=1000, max_length=8),
            preserve_default=False,
        ),
    ]
