# Generated by Django 4.2.6 on 2023-11-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0015_worker_req_wages'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor_req',
            name='servicestatus',
            field=models.BooleanField(default=True),
        ),
    ]
