# Generated by Django 4.2.6 on 2023-11-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0016_contractor_req_servicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor_req',
            name='Rate',
            field=models.CharField(default=1000, max_length=8),
            preserve_default=False,
        ),
    ]
