# Generated by Django 4.2.6 on 2023-11-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0019_contractor_maintence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_req',
            name='workstatus',
            field=models.BooleanField(default=False),
        ),
    ]
