# Generated by Django 4.2.6 on 2023-11-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0021_alter_contractor_req_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor_req',
            name='Rate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker_req',
            name='Wages',
            field=models.CharField(max_length=100),
        ),
    ]
